<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '所有项目',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '27',
    'cat_name' => '天花',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  2 => 
  array (
    'cat_id' => '28',
    'cat_name' => '地面',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '29',
    'cat_name' => '墙面',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '30',
    'cat_name' => '隔断',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '31',
    'cat_name' => '前台',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '32',
    'cat_name' => '办公家私',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '33',
    'cat_name' => '门',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '34',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '35',
    'cat_name' => '强电弱电',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '36',
    'cat_name' => '卫生间',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '37',
    'cat_name' => '软装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '38',
    'cat_name' => '配件辅料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>