<?php
$data = array (
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '男性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '86',
    'name' => '男性用品',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '飞机杯',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 1,
    'id' => '88',
    'name' => '飞机杯',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '女优名器',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '29',
    'level' => 1,
    'id' => '89',
    'name' => '女优名器',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '臀胸倒模',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 22,
    'level' => 1,
    'id' => '90',
    'name' => '臀胸倒模',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '助勃增大',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '91',
    'name' => '助勃增大',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '延时喷剂',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 1,
    'id' => '100',
    'name' => '延时喷剂',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '前列腺刺激',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '102',
    'name' => '前列腺刺激',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '充气娃娃',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '103',
    'name' => '充气娃娃',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '锁精套环',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 40,
    'level' => 1,
    'id' => '105',
    'name' => '锁精套环',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '实体玩偶',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 34,
    'level' => 1,
    'id' => '106',
    'name' => '实体玩偶',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '女性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '92',
    'name' => '女性用品',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '多点按摩棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '62',
    'level' => 1,
    'id' => '93',
    'name' => '多点按摩棒',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '仿真阳具',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 52,
    'level' => 1,
    'id' => '94',
    'name' => '仿真阳具',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '转珠棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '95',
    'name' => '转珠棒',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'G点振动棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 66,
    'level' => 1,
    'id' => '96',
    'name' => 'G点振动棒',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '性爱机器',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 9,
    'level' => 1,
    'id' => '97',
    'name' => '性爱机器',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '跳蛋',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 61,
    'level' => 1,
    'id' => '98',
    'name' => '跳蛋',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '情欲提升',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '99',
    'name' => '情欲提升',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => 'AV振动棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '101',
    'name' => 'AV振动棒',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '双乳刺激',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 17,
    'level' => 1,
    'id' => '104',
    'name' => '双乳刺激',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '后庭拉珠',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 18,
    'level' => 1,
    'id' => '107',
    'name' => '后庭拉珠',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '充气男人',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '108',
    'name' => '充气男人',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '私处挑逗',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 29,
    'level' => 1,
    'id' => '109',
    'name' => '私处挑逗',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '延时助情',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '110',
    'name' => '延时助情',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '延时喷剂',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 20,
    'level' => 1,
    'id' => '111',
    'name' => '延时喷剂',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '情欲提升',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '情欲提升',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '助勃增大',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '助勃增大',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '情趣服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '114',
    'name' => '情趣服饰',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '性感裙装',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '105',
    'level' => 1,
    'id' => '115',
    'name' => '性感裙装',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '制服诱惑',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 33,
    'level' => 1,
    'id' => '116',
    'name' => '制服诱惑',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '三点激情',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 53,
    'level' => 1,
    'id' => '117',
    'name' => '三点激情',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '情趣内裤',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '86',
    'level' => 1,
    'id' => '118',
    'name' => '情趣内裤',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '连体网衣',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 52,
    'level' => 1,
    'id' => '119',
    'name' => '连体网衣',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '情趣丝袜',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 44,
    'level' => 1,
    'id' => '120',
    'name' => '情趣丝袜',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '男士内衣',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '121',
    'name' => '男士内衣',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '双人情趣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '122',
    'name' => '双人情趣',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '体位道具',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '123',
    'name' => '体位道具',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '男女共震器',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 20,
    'level' => 1,
    'id' => '124',
    'name' => '男女共震器',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '捆绑束缚',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 22,
    'level' => 1,
    'id' => '125',
    'name' => '捆绑束缚',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '贞操裤',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 1,
    'id' => '126',
    'name' => '贞操裤',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '同性用品',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 13,
    'level' => 1,
    'id' => '127',
    'name' => '同性用品',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '手脚拷环',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 22,
    'level' => 1,
    'id' => '128',
    'name' => '手脚拷环',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '乳夹口塞',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 46,
    'level' => 1,
    'id' => '129',
    'name' => '乳夹口塞',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '头套眼罩',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 13,
    'level' => 1,
    'id' => '130',
    'name' => '头套眼罩',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '鞭打',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 21,
    'level' => 1,
    'id' => '131',
    'name' => '鞭打',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '另类调教',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 34,
    'level' => 1,
    'id' => '132',
    'name' => '另类调教',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'SM套装',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 22,
    'level' => 1,
    'id' => '133',
    'name' => 'SM套装',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '后庭肛塞',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 12,
    'level' => 1,
    'id' => '134',
    'name' => '后庭肛塞',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '润滑液',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '135',
    'name' => '润滑液',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '人体润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 39,
    'level' => 1,
    'id' => '136',
    'name' => '人体润滑液',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '唇吸润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 1,
    'id' => '137',
    'name' => '唇吸润滑液',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '后庭润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 8,
    'level' => 1,
    'id' => '138',
    'name' => '后庭润滑液',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '防过敏润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 1,
    'id' => '139',
    'name' => '防过敏润滑液',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '玩具清洗液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '140',
    'name' => '玩具清洗液',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '避孕套',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '10',
    'goods_num' => '1',
    'level' => 0,
    'id' => '141',
    'name' => '避孕套',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '超薄体贴',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 23,
    'level' => 1,
    'id' => '142',
    'name' => '超薄体贴',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '创意时尚',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 11,
    'level' => 1,
    'id' => '143',
    'name' => '创意时尚',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '倍爽润滑',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 1,
    'id' => '144',
    'name' => '倍爽润滑',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '紧致贴合',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 1,
    'id' => '145',
    'name' => '紧致贴合',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '女用特色',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 1,
    'id' => '146',
    'name' => '女用特色',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '冰火果味',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 33,
    'level' => 1,
    'id' => '147',
    'name' => '冰火果味',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '浮点颗粒',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 22,
    'level' => 1,
    'id' => '148',
    'name' => '浮点颗粒',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '超凡持久',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 13,
    'level' => 1,
    'id' => '149',
    'name' => '超凡持久',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '螺纹刺激',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 17,
    'level' => 1,
    'id' => '150',
    'name' => '螺纹刺激',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '超值组合',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 1,
    'id' => '151',
    'name' => '超值组合',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '丰胸缩阴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '152',
    'name' => '丰胸缩阴',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '缩阴养颜',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 23,
    'level' => 1,
    'id' => '153',
    'name' => '缩阴养颜',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '丰胸美胸',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '154',
    'name' => '丰胸美胸',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '私处护理',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '155',
    'name' => '私处护理',
  ),
);
?>