<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '所有项目',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '所有项目',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '设计',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '23',
    'name' => '设计',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '施工',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '施工',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '监理',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '监理',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '物料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '物料',
  ),
);
?>