<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '所有项目',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '所有项目',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '天花',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '27',
    'name' => '天花',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '地面',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '地面',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '墙面',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '墙面',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '隔断',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '隔断',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '前台',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '前台',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '办公家私',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '办公家私',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '门',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '门',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '灯具',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '强电弱电',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '强电弱电',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '卫生间',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '卫生间',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '软装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '软装',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '配件辅料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '配件辅料',
  ),
);
?>