<?php
$data = array (
  0 => 
  array (
    'cat_id' => '114',
    'content' => '',
    'cat_name' => '新手入站',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'xsrz',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  1 => 
  array (
    'cat_id' => '121',
    'content' => '',
    'cat_name' => '工程质量',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'gczl',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '119',
    'content' => '',
    'cat_name' => '工程预算',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'gcys',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '120',
    'content' => '',
    'cat_name' => '研发中心',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'yfzx',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '123',
    'content' => '',
    'cat_name' => '了解唐流',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'about',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  5 => 
  array (
    'cat_id' => '124',
    'content' => '',
    'cat_name' => '工装知识',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'gzzs',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '122',
    'content' => '',
    'cat_name' => '服务中心',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'fwzx',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  7 => 
  array (
    'cat_id' => '125',
    'content' => '',
    'cat_name' => '热点区域',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'rdqy',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '130',
    'content' => '',
    'cat_name' => '热点新闻',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'news',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '134',
    'content' => '',
    'cat_name' => '风格中心',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'fgzx',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '126',
    'content' => '',
    'cat_name' => '设计知识',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '124',
    'define_url' => 'sjzs',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  11 => 
  array (
    'cat_id' => '127',
    'content' => '',
    'cat_name' => '风水设计',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '124',
    'define_url' => 'fssj',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  12 => 
  array (
    'cat_id' => '128',
    'content' => '',
    'cat_name' => '材料知识',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '124',
    'define_url' => 'clzs',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  13 => 
  array (
    'cat_id' => '129',
    'content' => '',
    'cat_name' => '装修攻略',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '124',
    'define_url' => 'zxgl',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '135',
    'content' => '',
    'cat_name' => '热装地图',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '125',
    'define_url' => 'rzdt',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  15 => 
  array (
    'cat_id' => '136',
    'content' => '',
    'cat_name' => '在建工地',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '125',
    'define_url' => 'zjgd',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  16 => 
  array (
    'cat_id' => '137',
    'content' => '',
    'cat_name' => '客户见证',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '125',
    'define_url' => 'khjz',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  17 => 
  array (
    'cat_id' => '131',
    'content' => '',
    'cat_name' => '媒体合作',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '130',
    'define_url' => 'mthz',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  18 => 
  array (
    'cat_id' => '132',
    'content' => '',
    'cat_name' => '品牌咨讯',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '130',
    'define_url' => 'ppzx',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  19 => 
  array (
    'cat_id' => '133',
    'content' => '',
    'cat_name' => '装修知识',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '130',
    'define_url' => 'zxzs',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
);
?>