<?php
$data = array (
  0 => 
  array (
    'cat_id' => '32',
    'content' => '',
    'cat_name' => '关于我们',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'about',
    'moban' => '',
    'smallmoban' => 'about',
    'mmoban' => '',
    'msmallmoban' => 'about',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  1 => 
  array (
    'cat_id' => '107',
    'content' => '',
    'cat_name' => '常识中心',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'news',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '108',
    'content' => '',
    'cat_name' => '帮助中心',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'help',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '114',
    'content' => '',
    'cat_name' => '成人用品资讯',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'zx',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  4 => 
  array (
    'cat_id' => '115',
    'content' => '',
    'cat_name' => '客服服务',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'define_url' => 'kehu',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '109',
    'content' => '',
    'cat_name' => '使用帮助',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '108',
    'define_url' => 'use',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '110',
    'content' => '',
    'cat_name' => '购物保障',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '108',
    'define_url' => 'gouwu',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '111',
    'content' => '',
    'cat_name' => '支付方式',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '108',
    'define_url' => 'pay',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  8 => 
  array (
    'cat_id' => '112',
    'content' => '',
    'cat_name' => '私密快送',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '108',
    'define_url' => 'private',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  9 => 
  array (
    'cat_id' => '113',
    'content' => '',
    'cat_name' => '客户服务',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '108',
    'define_url' => 'fuwu',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  10 => 
  array (
    'cat_id' => '116',
    'content' => '',
    'cat_name' => '订单服务',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '115',
    'define_url' => 'oderfuwu',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  11 => 
  array (
    'cat_id' => '117',
    'content' => '',
    'cat_name' => '售后服务',
    'title_define' => '',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '115',
    'define_url' => 'shfuwu',
    'moban' => '',
    'smallmoban' => '',
    'mmoban' => '',
    'msmallmoban' => '',
    'file_url' => '',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>