<?php
$data = array (
  0 => 
  array (
    'cat_id' => '86',
    'cat_name' => '男性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '92',
    'cat_name' => '女性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '110',
    'cat_name' => '延时助情',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '114',
    'cat_name' => '情趣服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '122',
    'cat_name' => '双人情趣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '135',
    'cat_name' => '润滑液',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '141',
    'cat_name' => '避孕套',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '10',
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '152',
    'cat_name' => '丰胸缩阴',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '88',
    'cat_name' => '飞机杯',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '10',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '55',
  ),
  9 => 
  array (
    'cat_id' => '89',
    'cat_name' => '女优名器',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '30',
  ),
  10 => 
  array (
    'cat_id' => '90',
    'cat_name' => '臀胸倒模',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  11 => 
  array (
    'cat_id' => '91',
    'cat_name' => '助勃增大',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  12 => 
  array (
    'cat_id' => '100',
    'cat_name' => '延时喷剂',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '20',
  ),
  13 => 
  array (
    'cat_id' => '102',
    'cat_name' => '前列腺刺激',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  14 => 
  array (
    'cat_id' => '103',
    'cat_name' => '充气娃娃',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  15 => 
  array (
    'cat_id' => '105',
    'cat_name' => '锁精套环',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 40,
  ),
  16 => 
  array (
    'cat_id' => '106',
    'cat_name' => '实体玩偶',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 34,
  ),
  17 => 
  array (
    'cat_id' => '93',
    'cat_name' => '多点按摩棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '62',
  ),
  18 => 
  array (
    'cat_id' => '94',
    'cat_name' => '仿真阳具',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 52,
  ),
  19 => 
  array (
    'cat_id' => '95',
    'cat_name' => '转珠棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '16',
  ),
  20 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'G点振动棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 66,
  ),
  21 => 
  array (
    'cat_id' => '97',
    'cat_name' => '性爱机器',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 9,
  ),
  22 => 
  array (
    'cat_id' => '98',
    'cat_name' => '跳蛋',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 61,
  ),
  23 => 
  array (
    'cat_id' => '99',
    'cat_name' => '情欲提升',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  24 => 
  array (
    'cat_id' => '101',
    'cat_name' => 'AV振动棒',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  25 => 
  array (
    'cat_id' => '104',
    'cat_name' => '双乳刺激',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 17,
  ),
  26 => 
  array (
    'cat_id' => '107',
    'cat_name' => '后庭拉珠',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 18,
  ),
  27 => 
  array (
    'cat_id' => '108',
    'cat_name' => '充气男人',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  28 => 
  array (
    'cat_id' => '109',
    'cat_name' => '私处挑逗',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 30,
  ),
  29 => 
  array (
    'cat_id' => '111',
    'cat_name' => '延时喷剂',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 20,
  ),
  30 => 
  array (
    'cat_id' => '112',
    'cat_name' => '情欲提升',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '113',
    'cat_name' => '助勃增大',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '115',
    'cat_name' => '性感裙装',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '105',
  ),
  33 => 
  array (
    'cat_id' => '116',
    'cat_name' => '制服诱惑',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 33,
  ),
  34 => 
  array (
    'cat_id' => '117',
    'cat_name' => '三点激情',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 53,
  ),
  35 => 
  array (
    'cat_id' => '118',
    'cat_name' => '情趣内裤',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '86',
  ),
  36 => 
  array (
    'cat_id' => '119',
    'cat_name' => '连体网衣',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 52,
  ),
  37 => 
  array (
    'cat_id' => '120',
    'cat_name' => '情趣丝袜',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 44,
  ),
  38 => 
  array (
    'cat_id' => '121',
    'cat_name' => '男士内衣',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  39 => 
  array (
    'cat_id' => '123',
    'cat_name' => '体位道具',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  40 => 
  array (
    'cat_id' => '124',
    'cat_name' => '男女共震器',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 20,
  ),
  41 => 
  array (
    'cat_id' => '125',
    'cat_name' => '捆绑束缚',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  42 => 
  array (
    'cat_id' => '126',
    'cat_name' => '贞操裤',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  43 => 
  array (
    'cat_id' => '127',
    'cat_name' => '同性用品',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 13,
  ),
  44 => 
  array (
    'cat_id' => '128',
    'cat_name' => '手脚拷环',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  45 => 
  array (
    'cat_id' => '129',
    'cat_name' => '乳夹口塞',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 46,
  ),
  46 => 
  array (
    'cat_id' => '130',
    'cat_name' => '头套眼罩',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 13,
  ),
  47 => 
  array (
    'cat_id' => '131',
    'cat_name' => '鞭打',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 21,
  ),
  48 => 
  array (
    'cat_id' => '132',
    'cat_name' => '另类调教',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 34,
  ),
  49 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'SM套装',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  50 => 
  array (
    'cat_id' => '134',
    'cat_name' => '后庭肛塞',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 12,
  ),
  51 => 
  array (
    'cat_id' => '136',
    'cat_name' => '人体润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 39,
  ),
  52 => 
  array (
    'cat_id' => '137',
    'cat_name' => '唇吸润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  53 => 
  array (
    'cat_id' => '138',
    'cat_name' => '后庭润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  54 => 
  array (
    'cat_id' => '139',
    'cat_name' => '防过敏润滑液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 7,
  ),
  55 => 
  array (
    'cat_id' => '140',
    'cat_name' => '玩具清洗液',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  56 => 
  array (
    'cat_id' => '142',
    'cat_name' => '超薄体贴',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 23,
  ),
  57 => 
  array (
    'cat_id' => '143',
    'cat_name' => '创意时尚',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 11,
  ),
  58 => 
  array (
    'cat_id' => '144',
    'cat_name' => '倍爽润滑',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  59 => 
  array (
    'cat_id' => '145',
    'cat_name' => '紧致贴合',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  60 => 
  array (
    'cat_id' => '146',
    'cat_name' => '女用特色',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 7,
  ),
  61 => 
  array (
    'cat_id' => '147',
    'cat_name' => '冰火果味',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 33,
  ),
  62 => 
  array (
    'cat_id' => '148',
    'cat_name' => '浮点颗粒',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 22,
  ),
  63 => 
  array (
    'cat_id' => '149',
    'cat_name' => '超凡持久',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 13,
  ),
  64 => 
  array (
    'cat_id' => '150',
    'cat_name' => '螺纹刺激',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 17,
  ),
  65 => 
  array (
    'cat_id' => '151',
    'cat_name' => '超值组合',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  66 => 
  array (
    'cat_id' => '153',
    'cat_name' => '缩阴养颜',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 23,
  ),
  67 => 
  array (
    'cat_id' => '154',
    'cat_name' => '丰胸美胸',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  68 => 
  array (
    'cat_id' => '155',
    'cat_name' => '私处护理',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '10',
  ),
);
?>