var page_h=document.domain;
var page_t=$(document).attr("title");
var isIE6=navigator.appVersion.indexOf("MSIE 6")>-1;
if(isIE6){document.execCommand("BackgroundImageCache",false,true);}
var $lnav=$("#lnav");
var pez="top=100,left=100,width=1000,height=580,location=yes,menubar=no,location=no,resizable=yes,scrollbars=yes,status=no,toolbar=no";
(function($){$.fn.vganload=function(options){var dft={author:"vganchou",timew:10,threshold:100};var ops=$.extend(dft,options);var mb=this;var m_l=mb.length;var mlen=m_l;var poll;var tm_w=ops.timew;var thre=ops.threshold;var vlazy={};if(m_l<1){return}function getClient(){var l,t,w,h,dd=document.documentElement,bb=document.body;l=dd.scrollLeft||bb.scrollLeft;t=dd.scrollTop||bb.scrollTop;w=dd.clientWidth;h=dd.clientHeight;return{left:l,top:t,width:w,height:h}}function getSubClient(p){var l=0,t=0,w,h;w=p.offsetWidth;h=p.offsetHeight;while(p.offsetParent){l+=p.offsetLeft;t+=p.offsetTop;p=p.offsetParent}return{left:l,top:t,width:w,height:h}}function intens(w,p){var lc1,lc2,tc1,tc2,w1,h1;lc1=w.left+w.width/2;lc2=p.left+p.width/2;tc1=w.top+w.height/2;tc2=p.top+p.height/2;w1=(w.width+p.width)/2;h1=(w.height+p.height)/2;return Math.abs(lc1-lc2)<w1+thre&&Math.abs(tc1-tc2)<h1+thre}var vbone=function(){clearTimeout(poll);poll=setTimeout(vlazy.render,tm_w)};$(window).bind("scroll",vbone).bind("resize",vbone);vlazy.detach=function(){$(window).unbind("scroll",vbone).unbind("resize",vbone);clearTimeout(poll)};vlazy.render=function(){if(mlen<1){vlazy.detach();return}var prec1=getClient();mb=mb.filter(function(){return $(this).attr("src2")});$.each(mb,function(){var b=$(this).attr("src2");if(b){var prec2=getSubClient(this);var inv=intens(prec1,prec2);if(inv){$(this).attr("src",b).removeAttr("src2");mlen--}}})};vlazy.render()}})(jQuery);
(function(root,factory){if(typeof define==="function"&&define.amd){define(function(){return factory(root)})}else{if(typeof exports==="object"){module.exports=factory}else{root.qufloor=factory(root)}}})(this,function(root){var qufloor={};var f_of=[];var f_rf=[];var f_zt=[];var floors=[];var dlen,cur=0,iscroll=false,nav,gtp,ofpx,ite,curclass;var wh=$(window).height();var mwh=wh/2;qufloor.addof=function(arr){dlen=arr.length;for(var i=0;i<dlen;i++){var t=Math.floor($("#"+arr[i]).offset().top);var th=Math.floor($("#"+arr[i]).height());f_of.push(t);f_rf.push(th);f_zt.push(0)}f_zt[0]=1};qufloor.init=function(opts){opts=opts||{};ofpx=opts.ofpx||80;curclass=opts.cur_class||"current";nav=$("#"+opts.nav);ite=nav.find("a");gtp=$("#"+opts.top_id);ite.each(function(){var hr=$(this).attr("href").split("#")[1];floors.push(hr)});qufloor.addof(floors);ite.click(function(event){var i=$(this).index();if(i==cur){return}var ta=(wh-f_rf[i])/2;var tb=f_of[i]-ta;var tc=tb>0?tb:0;var j=ta>0?tc:f_of[i];$(this).addClass(curclass).siblings().removeClass(curclass);iscroll=true;$("body,html").stop().animate({scrollTop:j},300,function(){iscroll=false;qufloor.reseta(i)});event.preventDefault()});gtp.bind("click",function(event){iscroll=true;$("body,html").stop().animate({scrollTop:0},300,function(){f_zt[cur]=0;cur=0;ite.removeClass(curclass);iscroll=false});event.preventDefault()});$(window).scroll(function(){var s_top=$(window).scrollTop();var tp=s_top+mwh;var e=qufloor.arrbs(f_of,tp,0,dlen-1);if(f_zt[e]!=1&&!iscroll){ite.eq(e).addClass(curclass).siblings().removeClass(curclass);qufloor.reseta(e)}if(f_rf[cur]+f_of[cur]<tp-ofpx){ite.eq(cur).removeClass(curclass);f_zt[cur]=0}});$(window).resize(function(){wh=$(window).height();mwh=wh/2})};qufloor.reseta=function(e){for(var i=0;i<dlen;i++){f_zt[i]=0}f_zt[e]=1;cur=e};qufloor.arrbs=function(arr,avl,li,ri){if(li>ri){var f=li-1;return f}var mi=Math.floor((li+ri)/2);var miv=arr[mi];if(miv>avl){return qufloor.arrbs(arr,avl,li,mi-1)}else{if(miv<avl){return qufloor.arrbs(arr,avl,mi+1,ri)}else{var f=mi+1;return f}}};return qufloor});
function gotop(){$('html,body').stop().animate({scrollTop:'0px'},600);}
$(function(){
$("img[src2]").vganload({type:"image"});
var $yvv = $("#keywords");
var $lnav=$("#lnav");
var $lnavli=$lnav.children();
var $yvv=$("#keywords");$yvv.bind("focus",function(){var v=$(this).val();var preh=$(this).attr("data-w");if(v==preh){$(this).val("");$(this).addClass("c3")}}).bind("blur",function(){var v=$(this).val();var preh=$(this).attr("data-w");if(v==""){$(this).val(preh);$(this).removeClass("c3")}});
$lnavli.hover(function(){$(this).addClass("con");},function(){$(this).removeClass("con");});
$("#tul").delegate(".nbt","hover",function(event){var tl=$(this);if(event.type=="mouseenter"){tl.addClass("on")}else{tl.removeClass("on")}});$("#bignav").hover(function(){$lnav.show()},function(){$lnav.hide()});
if($("base").length>0){var dm="http://"+document.domain+"/";if(dm!=$("base").attr("href")){$("base").attr("href",dm);}}	
});
function lgout(){$.get('user.php',{act:'ajax_logout'},function(data){if(data=="TRUE"){location.reload();}},'TEXT');}
function jieshou(a){var curl="http://"+page_h+"/chats.php?pagetitle="+page_t;window.open(curl,'在线客服',pez);}
function topic_addCar(e,a,c){var d=false;if(c==undefined){d=false}else{d=c}if(isNaN(e)){alert("非法id");return}if(a==undefined){a=""}var b='{"quick":1,"spec":["'+a+'"],"goods_id":'+e+',"number":"1","isgo":"1","parent":0}';$.post("/flow.php",{step:"add_to_cart",one:0,goods:b},function(f){if(f.error>0){if(f.error==2){if(confirm(f.message)){alert("对不起该商品缺货，敬请等待...")}}else{if(f.error==6){alert("请选择商品规格")}else{alert(f.message)}}}else{alert("恭喜您，添加成功！");if(d){location.href="/flow.php"}}},"JSON")}function topic_package(b,c){var d=false;if(c==undefined){d=false}else{d=c}var a='{"package_id":'+b+',"number":1}';$.post("/flow.php",{step:"add_package_to_cart",package_info:a},function(e){if(e.error>0){if(e.error==2){if(confirm(e.message)){location.href="user.php?act=add_booking&id="+e.goods_id}}else{alert(e.message)}}else{alert("恭喜您，添加成功！");if(d){location.href="/flow.php"}}},"JSON")}function getCoupon(a){$.post("topic.php",{step:"get_bun",id:a},function(b){if(b.error!=1){if(b.error==2){alert("请先登录后领取红包")}if(b.error==3){alert("您已经领取过该红包了")}}else{alert("恭喜您，领取成功！")}},"JSON")};